# Generated by Django 3.0.8 on 2021-10-25 20:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('navbar1', '0003_tutorialseries'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TutorialSeries',
            new_name='submitted_detail',
        ),
    ]
