# Generated by Django 3.0.8 on 2021-10-25 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('navbar1', '0004_auto_20211026_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitted_detail',
            name='match_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navbar1.update_matches'),
        ),
        migrations.AlterField(
            model_name='submitted_detail',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
