# Generated by Django 3.0.8 on 2021-10-27 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navbar1', '0006_submitted_detail_match_key_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitted_detail',
            name='match_key_id',
        ),
    ]
