# Generated by Django 3.2.9 on 2021-11-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar1', '0011_auto_20211106_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='results_update_final',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('flag1', models.CharField(max_length=100)),
                ('flag2', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='final_results_update',
        ),
        migrations.DeleteModel(
            name='results_update_flag',
        ),
    ]
